using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.SceneManagement;

public class PlayerStats : MonoBehaviour, IDataPersistence
{
    public CharacterScriptableObject characterData;
    public float currentHealth;
    public float currentMoveSpeed;

    [Header("I-Frames")]
    public float invincibilityDuration;
    public float invincibilityTimer;
    public bool isInvincible;

    public int gold;

    public static PlayerStats Instance; 

    private PlayerLevel playerLevel;

    public int experience;
    public int level;
    public int experienceCap;

    void Start()
    {
        playerLevel = FindObjectOfType<PlayerLevel>();
        experience = playerLevel.experience;
        level = playerLevel.level;
        experienceCap = playerLevel.experienceCap;
    }

    public void LoadData(GameData data)
    {
        this.gold = data.gold;
        this.level = data.level;
        this.experience = data.experience;
        this.experienceCap = data.experienceCap;
    }

    public void SaveData(GameData data)
    {
         
    }

    public void IncreaseGold(int amount)
    {
        gold += amount; 
    }

    void Update()
    {
        if(invincibilityTimer > 0)
        {
            invincibilityTimer -= Time.deltaTime;
        }
        else if(isInvincible)
        {
            isInvincible = false;
        }
    }

    void Awake()
    {
        Instance = this;
        currentHealth = characterData.MaxHealth;
        currentMoveSpeed = characterData.MoveSpeed;
    } 

    public void TakeDamage(float dmg)
    {
        if(!isInvincible)
        {
            currentHealth -= dmg;

            invincibilityTimer = invincibilityDuration;
            isInvincible = true;

            if(currentHealth <= 0)
            {
                Kill();
            }
        }
    }

    public void Kill()
    {
        gold /= 5;
        Destroy(gameObject);
        SceneManager.LoadScene("Lobby");
    }

    public void RestoreHealth(float amount)
    {
        if(currentHealth < characterData.MaxHealth)
        {
            currentHealth += amount;

            if(currentHealth > characterData.MaxHealth)
            {
                currentHealth = characterData.MaxHealth;
            }
        }
    }
}
